const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const titles={home:"Beranda",create:"Buat Klip AI",analysis:"Analisis Potensi FYP",captions:"Subtitle & Judul",history:"Riwayat Klip",support:"Tanya ClipCepat AI"};
function go(view){$$(".view").forEach(x=>x.classList.add("hidden"));$("#view-"+view)?.classList.remove("hidden");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#pageTitle").textContent=titles[view]||"ClipCepat AI";$(".sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
$$("[data-view]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.view)));$$("[data-go]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.go)));$("#menuToggle").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));
let toastTimer;function toast(s){const t=$("#toast");t.textContent=s;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
function validYoutube(s){try{const u=new URL(s);return ["youtube.com","www.youtube.com","m.youtube.com","youtu.be","www.youtube-nocookie.com"].includes(u.hostname)&&(/\/watch/.test(u.pathname)||/youtu\.be/.test(u.hostname)||/\/shorts\//.test(u.pathname)||/\/live\//.test(u.pathname))}catch{return false}}
$("#pasteBtn").addEventListener("click",async()=>{try{const t=await navigator.clipboard.readText();$("#youtubeUrl").value=t;toast("Tautan ditempel")}catch{ $("#youtubeUrl").focus();toast("Tempel tautan menggunakan menu Tempel di keyboard") }});
$("#createBtn").addEventListener("click",()=>{const url=$("#youtubeUrl").value.trim(),r=$("#createResult");r.classList.remove("hidden");if(!validYoutube(url)){r.innerHTML="<b>Tautan belum valid</b>Masukkan URL YouTube yang benar, misalnya https://www.youtube.com/watch?v=...";return}r.innerHTML="<b>Antarmuka siap — backend belum terhubung</b>URL berhasil dikenali. Agar klip asli dapat dibuat, website perlu backend untuk mengambil sumber video yang sah, memprosesnya dengan FFmpeg atau layanan setara, menjalankan analisis AI, dan menyimpan hasil unduhan. Tidak ada video yang diunduh pada demo ini.<p><b>Pengaturan pilihan:</b> "+esc($("#duration").value)+" · "+esc($("#format").value)+" · "+esc($("#quality").value)+" · "+esc($("#goal").value)+"</p>";});
$("#analyzeBtn").addEventListener("click",()=>{const topic=$("#analysisTopic").value.trim(),r=$("#analysisResult");r.classList.remove("hidden");r.className="result-box";if(!topic){r.textContent="Masukkan ringkasan atau topik video terlebih dahulu.";return}r.innerHTML="<b>Contoh saran awal (bukan hasil analisis AI)</b><p>• Buka dengan pertanyaan, fakta mengejutkan, atau konflik yang relevan.</p><p>• Pastikan satu ide utama mudah dipahami.</p><p>• Gunakan subtitle kontras dan hindari teks terlalu rapat.</p><p>• Buat penutup yang memberi alasan untuk menonton sampai akhir.</p><small>Untuk analisis konten sesungguhnya, sambungkan transkripsi/analisis AI melalui backend.</small>";});
$("#captionBtn").addEventListener("click",()=>{const topic=$("#captionTopic").value.trim(),r=$("#captionResult");r.classList.remove("hidden");r.className="result-box";if(!topic){r.textContent="Isi topik video dulu.";return}const p=$("#platform").value;r.innerHTML="<b>Draf teks contoh — "+esc(p)+"</b><p><strong>Judul:</strong> "+esc(topic)+" — hal yang perlu kamu tahu</p><p><strong>Caption:</strong> Simak sampai akhir untuk memahami "+esc(topic.toLowerCase())+". Apa pendapatmu? Tulis di komentar.</p><p><strong>Hashtag:</strong> #Shorts #VideoIndonesia #"+slug(topic)+"</p><small>Ini template sederhana. API AI diperlukan untuk menghasilkan rekomendasi dinamis yang lebih relevan.</small>";});
function slug(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]/g,"").slice(0,24)||"Konten"}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
const faq=[
{keys:["cara membuat","buat klip","membuat klip","cara menggunakan","mulai"],answer:"Untuk memulai, buka menu Buat Klip AI, masukkan tautan YouTube yang valid, lalu pilih durasi, format, kualitas, dan fokus klip. Pada versi awal ini tombol hanya memvalidasi tautan. Backend pemrosesan video harus dihubungkan sebelum klip asli dapat dibuat."},
{keys:["2k","1080","resolusi","kualitas","hd"],answer:"Antarmuka menyediakan pilihan 720p, 1080p, dan 2K jika didukung. Resolusi hasil bergantung pada sumber video dan mesin pemrosesan. Pilihan resolusi di demo ini belum menjalankan ekspor video."},
{keys:["unduh","download","belum bisa","video jadi","hasil klip"],answer:"Klip belum bisa diunduh karena versi awal belum terhubung ke backend video. Diperlukan layanan pemrosesan video, penyimpanan hasil, dan endpoint aman untuk membuat tautan unduhan."},
{keys:["fyp","viral","analisis"],answer:"Analisis potensi FYP dapat menilai hook, alur cerita, tempo, subtitle, dan relevansi topik. AI tidak dapat menjamin FYP atau viral. Analisis otomatis membutuhkan transkrip atau konten yang bisa diakses secara sah dan API AI."},
{keys:["subtitle","caption","hashtag","judul"],answer:"Menu Subtitle & Judul saat ini menghasilkan template sederhana. Untuk subtitle dari ucapan video dan rekomendasi teks yang dinamis, hubungkan layanan speech-to-text dan API AI melalui backend."},
{keys:["gratis","biaya","bayar"],answer:"Antarmuka dan hosting statis dapat dimulai dengan paket gratis. Pemrosesan video berat, penyimpanan, transkripsi, dan API AI mungkin memiliki batas gratis atau biaya. Periksa batas layanan sebelum dipublikasikan."},
{keys:["youtube","hak cipta","izin","copyright"],answer:"Gunakan video milikmu atau video yang izinnya kamu miliki. Tautan publik tidak otomatis memberi hak untuk mengunduh atau mengolah video. Integrasi harus mematuhi ketentuan YouTube dan hukum hak cipta."},
{keys:["api","backend","aktif","berfungsi"],answer:"Website ini adalah frontend siap unggah ke Cloudflare Pages. Pemrosesan URL menjadi klip dan jawaban AI generatif belum aktif; keduanya memerlukan backend/API. Jangan menaruh API key rahasia di JavaScript frontend."}
];
function supportAnswer(q){const s=q.toLowerCase();for(const item of faq){if(item.keys.some(k=>s.includes(k)))return item.answer}return "Maaf, saya hanya dapat membantu pertanyaan seputar penggunaan dan fitur ClipCepat AI. Kamu bisa bertanya tentang cara membuat klip, resolusi, subtitle, analisis FYP, biaya, atau kendala website."}
function addMessage(text,who){const d=document.createElement("div");d.className="message "+who;d.textContent=text;$("#chatMessages").appendChild(d);$("#chatMessages").scrollTop=$("#chatMessages").scrollHeight}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();const input=$("#chatInput"),q=input.value.trim();if(!q)return;addMessage(q,"user");input.value="";setTimeout(()=>addMessage(supportAnswer(q),"bot"),180)});
$$(".suggestion").forEach(b=>b.addEventListener("click",()=>{addMessage(b.textContent,"user");setTimeout(()=>addMessage(supportAnswer(b.textContent),"bot"),180)}));
